import { PublicPageShell } from "@/components/layout/PublicPageShell";
import { LocalizedText } from "@/components/i18n/LocalizedText";

const SECTIONS = [
  {
    title: { en: "1. Acceptance", ar: "1. القبول" },
    body: {
      en: "By creating an account or using Fazumi, you agree to these Terms. If you disagree, please do not use the service.",
      ar: "عند إنشاء حساب أو استخدام Fazumi فإنك توافق على هذه الشروط. وإذا كنت لا توافق عليها، يرجى عدم استخدام الخدمة.",
    },
  },
  {
    title: { en: "2. Permitted use", ar: "2. الاستخدام المسموح" },
    body: {
      en: "Fazumi is a personal productivity tool. You may use it to summarize group chats you are a participant in. You may not use Fazumi to process chats you are not authorised to access, or to build competing services.",
      ar: "Fazumi أداة إنتاجية شخصية. يمكنك استخدامها لتلخيص المحادثات الجماعية التي تكون مشاركًا فيها. ولا يجوز لك استخدام Fazumi لمعالجة محادثات غير مصرح لك بالوصول إليها أو لبناء خدمات منافسة.",
    },
  },
  {
    title: { en: "3. AI output disclaimer", ar: "3. إخلاء مسؤولية مخرجات الذكاء الاصطناعي" },
    body: {
      en: "Summaries are generated by AI and may contain errors or omissions. Do not rely on Fazumi summaries for urgent or safety-critical decisions. Always verify important information against the original source.",
      ar: "يتم إنشاء الملخصات بواسطة الذكاء الاصطناعي وقد تتضمن أخطاء أو سهوًا. لا تعتمد على ملخصات Fazumi في القرارات العاجلة أو الحساسة للسلامة. تحقق دائمًا من المعلومات المهمة بالرجوع إلى المصدر الأصلي.",
    },
  },
  {
    title: { en: "4. Subscriptions", ar: "4. الاشتراكات" },
    body: {
      en: "Paid plans renew automatically. You may cancel at any time from the Billing page. Cancellation takes effect at the end of the current billing period. Founder LTD purchases are one-time and non-refundable (see Refund Policy).",
      ar: "يتم تجديد الخطط المدفوعة تلقائيًا. ويمكنك الإلغاء في أي وقت من صفحة الفوترة. ويسري الإلغاء في نهاية فترة الفوترة الحالية. أما مشتريات Founder LTD فهي دفعة واحدة وغير قابلة للاسترداد، راجع سياسة الاسترداد.",
    },
  },
  {
    title: { en: "5. Liability", ar: "5. المسؤولية" },
    body: {
      en: 'Fazumi is provided "as is" without warranty. We are not liable for any loss or damage arising from your use of the service, including reliance on AI-generated summaries.',
      ar: "يتم تقديم Fazumi كما هو ودون أي ضمانات. ونحن غير مسؤولين عن أي خسارة أو ضرر ينشأ عن استخدامك للخدمة، بما في ذلك الاعتماد على الملخصات التي ينشئها الذكاء الاصطناعي.",
    },
  },
  {
    title: { en: "6. Termination", ar: "6. إنهاء الخدمة" },
    body: {
      en: "We may suspend or terminate your account if you violate these Terms. You may delete your account at any time from the Profile page.",
      ar: "يجوز لنا تعليق حسابك أو إنهاؤه إذا خالفت هذه الشروط. ويمكنك حذف حسابك في أي وقت من صفحة الملف الشخصي.",
    },
  },
  {
    title: { en: "7. Governing law", ar: "7. القانون الحاكم" },
    body: {
      en: "These Terms are governed by the laws of Qatar. Disputes will be resolved in the courts of Qatar, unless otherwise required by applicable law.",
      ar: "تخضع هذه الشروط لقوانين دولة قطر. ويتم الفصل في النزاعات أمام محاكم قطر ما لم يتطلب القانون المعمول به خلاف ذلك.",
    },
  },
  {
    title: { en: "8. Contact", ar: "8. التواصل" },
    body: {
      en: "Legal questions:",
      ar: "للاستفسارات القانونية:",
    },
    contact: "legal@fazumi.app",
  },
] as const;

export default function TermsPage() {
  return (
    <PublicPageShell
      eyebrow={{ en: "Legal", ar: "قانوني" }}
      title={{ en: "Terms of Service", ar: "شروط الخدمة" }}
      description={{ en: "The rules that govern your use of Fazumi.", ar: "القواعد التي تحكم استخدامك لـ Fazumi." }}
    >
      <div className="space-y-6 max-w-3xl">
        <p className="text-xs text-[var(--muted-foreground)]">
          <LocalizedText en="Last updated: March 2026" ar="آخر تحديث: مارس 2026" />
        </p>
        {SECTIONS.map((section) => (
          <section key={section.title.en}>
            <h2 className="mb-2 text-base font-semibold text-[var(--foreground)]">
              <LocalizedText en={section.title.en} ar={section.title.ar} />
            </h2>
            <p className="text-sm leading-7 text-[var(--muted-foreground)]">
              <LocalizedText en={section.body.en} ar={section.body.ar} />{" "}
              {"contact" in section && (
                <a href={`mailto:${section.contact}`} className="text-[var(--primary)] hover:underline">
                  {section.contact}
                </a>
              )}
            </p>
          </section>
        ))}
      </div>
    </PublicPageShell>
  );
}
