import { DashboardShell } from "@/components/layout/DashboardShell";
import { LocalizedText } from "@/components/i18n/LocalizedText";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <DashboardShell>
      <Card>
        <CardHeader>
          <CardTitle>
            <LocalizedText en="Terms of Service" ar="شروط الخدمة" />
          </CardTitle>
          <p className="text-xs text-[var(--muted-foreground)]">
            <LocalizedText en="Last updated: March 2026" ar="آخر تحديث: مارس 2026" />
          </p>
        </CardHeader>
        <CardContent className="space-y-6 text-[var(--foreground)]">
          <section>
            <h2 className="text-base font-semibold mb-2">1. Acceptance</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              By creating an account or using Fazumi, you agree to these Terms.
              If you disagree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">2. Permitted use</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Fazumi is a personal productivity tool. You may use it to summarize group chats
              you are a participant in. You may not use Fazumi to process chats you are not
              authorised to access, or to build competing services.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">3. AI output disclaimer</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Summaries are generated by AI and may contain errors or omissions.
              Do not rely on Fazumi summaries for urgent or safety-critical decisions.
              Always verify important information against the original source.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">4. Subscriptions</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Paid plans renew automatically. You may cancel at any time from the Billing page.
              Cancellation takes effect at the end of the current billing period.
              Founder LTD purchases are one-time and non-refundable (see Refund Policy).
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">5. Liability</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Fazumi is provided &quot;as is&quot; without warranty. We are not liable for any loss or
              damage arising from your use of the service, including reliance on AI-generated summaries.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">6. Termination</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              We may suspend or terminate your account if you violate these Terms.
              You may delete your account at any time from the Profile page.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">7. Governing law</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              These Terms are governed by the laws of Qatar. Disputes will be resolved
              in the courts of Qatar, unless otherwise required by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">8. Contact</h2>
            <p className="text-sm text-[var(--muted-foreground)]">
              Legal questions:{" "}
              <a href="mailto:legal@fazumi.app" className="text-[var(--primary)] hover:underline">
                legal@fazumi.app
              </a>
            </p>
          </section>
        </CardContent>
      </Card>
    </DashboardShell>
  );
}
